### ISSUE TITLE
Using Measurements, including errors in cosmology constants and redshift

### ISSUE THREAD

**Issue by yangcht** [JuliaAstro/Cosmology.jl#7]
Hello! I am a new Julia user, so this question may sound naive. I am using Julia v0.5 on Mac OSX 10.11.6 (15G1108), with the latest packages in Julia Astolibs. 

I want to do calculate the luminosity distance considering both the errors from the redshift measurement and also the errors from the cosmology constants (taking Planck 2015 results: H_0=68.9± 0.1 and OmegaM=0.308± 0.012), using the Julia package Measurements.jl and this Cosmology.jl.

I tried the following:

```Julia
julia> using Measurements

julia> using Cosmology

julia> c = cosmology(h=0.678± 0.009, OmegaM = 0.308± 0.012)
Cosmology.FlatLCDM{Measurements.Measurement{Float64}}(0.678 ± 0.009,0.6919090670178154 ± 0.012000000242838335,0.308 ± 0.012,9.093298218455683e-5 ± 2.4141499695015085e-6)

julia> luminosity_dist_mpc(c, 3.5651)
32007.785677876316 ± 573.8293114987347
```

It works. However, when I tried to include the error of the redshift, it gave errors:

```Julia
julia> luminosity_dist_mpc(c, 3.5651 ± 0.0006)
ERROR: MethodError: Cannot `convert` an object of type Measurements.Measurement{Float64} to an object of type Float64
This may have arisen from a call to the constructor Float64(...),
since type constructors fall back to convert methods.
 in eignewt(::Array{Measurements.Measurement{Float64},1}, ::Int64, ::Int64) at ./quadgk.jl:275
 in kronrod(::Type{Measurements.Measurement{Float64}}, ::Int64) at ./quadgk.jl:383
 in do_quadgk(::Cosmology.##2#3{Cosmology.FlatLCDM{Measurements.Measurement{Float64}}}, ::Array{Measurements.Measurement{Float64},1}, ::Int64, ::Type{Measurements.Measurement{Float64}}, ::Measurements.Measurement{Float64}, ::Float64, ::Int64, ::Base.LinAlg.#vecnorm) at ./quadgk.jl:116
 in #quadgk#15(::Array{Any,1}, ::Function, ::Function, ::Measurements.Measurement{Float64}, ::Int64) at ./quadgk.jl:230
 in Z(::Cosmology.FlatLCDM{Measurements.Measurement{Float64}}, ::Measurements.Measurement{Float64}) at /Users/yangcht/.julia/v0.5/Cosmology/src/Cosmology.jl:144
 in luminosity_dist_mpc(::Cosmology.FlatLCDM{Measurements.Measurement{Float64}}, ::Measurements.Measurement{Float64}) at /Users/yangcht/.julia/v0.5/Cosmology/src/Cosmology.jl:162
```

Do you have any clue about this?  Thank you!

**Comment by kbarbary** [comment]
It looks like the integration function (`quadgk`) doesn't support arbitrary types for the integral end point. (Here, the redshift is the upper limit on a definite integral.)

**Comment by yangcht** [comment]
Thanks for the prompt reply!
Is there a way to replace the following `quadgk` to something like `cuba`? I am not sure if `cuba ` include the function.

```Julia
Z(c::AbstractCosmology, z::Real) = ((q,_) = quadgk(a::Float64->1.0/a2E(c,a), scale_factor(z), 1); q)
```

**Comment by kbarbary** [comment]
Cuba wraps a C library, so I doubt it has the ability to deal with arbitrary types like `Measurement`.

**Comment by giordano** [comment]
Formally, the derivative of an integral with respect to the endpoints is well-known (and pretty easy).  I'm working on extending `Measurements.jl` to support `quadgk` with `Measurement`s endpoints.

**Comment by giordano** [comment]
I find it amazing that `quadgk` works out-of-the-box with functions returning arbitrary types, including `Measurement`.

I've merged my changes on `master`, will be live with next tagged release of `Measurements.jl` or if you check out `master` branch.  Note that next version of `Measurements.jl` will require Julia 0.6.  I've added a [bunch of tests](https://github.com/giordano/Measurements.jl/blob/6ca5919c07d1d097a669f7d03a0d3532f6a7bef6/test/runtests.jl#L483-L493) to be sure that results make sense (in the tests, `w`, `x`, and `y` are `Measurement` objects).

Now, `luminosity_dist_mpc` and friends work with a redshift with uncertainty, for example:
```
julia> luminosity_dist_mpc(cosmology(h=0.6774 ± 0.0046, OmegaM = 0.3089 ± 0.0062), 3.5651 ± 0.0006)
32007.199597491566 ± 294.61793058312304
```

**Comment by yangcht** [comment]
Hi! I am still getting errors like:

```
julia> luminosity_dist_mpc(cosmology(h=0.6774 ± 0.0046, OmegaM = 0.3089 ± 0.0062), 3.5651 ± 0.0006)
ERROR: quadgk(Cosmology.#2, 0.21905325184552363 ± 2.8790596286459042e-5, 1) has been moved to the package QuadGK.jl.
Run Pkg.add("QuadGK") to install QuadGK on Julia v0.6 and later, and then run `using QuadGK`.
```

I installed QuadGK.jl and then "using" it, but getting same errors. Is that because the code needs an update of "quadgk"?

Thank you.

**Comment by giordano** [comment]
Now that all PRs have been merged into master, I think that it should work.  After checking out `master` branches for both packages on Julia 0.6 (latest version of `Measurements.jl` requires it) I can do all the following:
```julia
julia> using Measurements, Cosmology

julia> cosmo = cosmology(h=0.6774 ± 0.0046, OmegaM = 0.3089 ± 0.0062)
Cosmology.FlatLCDM{Measurements.Measurement{Float64}}(0.6774 ± 0.0046, 0.6910089058605903 ± 0.006200000123436743, 0.3089 ± 0.0062, 9.109413940981078e-5 ± 1.2371805175232643e-6)

julia> z = 3.5651 ± 0.0006
3.5651 ± 0.0006

julia> luminosity_dist_mpc(cosmo, z)
32007.199597491566 ± 294.61793058312304

julia> age_gyr(cosmo, z)
1.7648721924469744 ± 0.02114474964318084

julia> lookback_time_gyr(cosmo, z)
12.032548576700925 ± 0.10148412665949445

julia> age_gyr(cosmo, 0)
13.797420769125996 ± 0.1216471655368799

julia> lookback_time_gyr(cosmo, z) + age_gyr(cosmo, z)
13.7974207691479 ± 0.12164814793142888
```
Can you please confirm?

**Comment by yangcht** [comment]
Thank you so much!!! It is now working perfectly!!!

**Comment by giordano** [comment]
Thanks for the confirmation. I'm closing the issue then.

**Comment by yangcht** [comment]
Indeed!
